### ISSUE TITLE
Error opening, 

### ISSUE THREAD

**Issue by Resaarts** [matheussampaio/ao-loot-logger#7]
"Error: The specified module could not be found.
C:\Users\***\AppData\Local\Temp\pkg\62577a1cfd6d8a4d76ee1a32aa6652298c484fd049c959a2cc29f66df0151511\cap\build\Release\cap.node
    at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\ao-loot-logger\node_modules\cap\lib\Cap.js:3:13)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'ERR_DLOPEN_FAILED'
}"

Getting this error attempting to open the 2.5.0 app. already reinstalled npcap without any resolution

**Comment by matheussampaio** [comment]
This bug is haunting us. I can't find a reliable fix to it. :/
